### ISSUE TITLE
Need to know the build & test procedure 

### ISSUE THREAD

**Issue by alloc7260** [yandeu/docker-swarm-visualizer#12]
Hi @yandeu ,
I found your repo amazingly helpful, 
but I want some more functionality on top like display hostname and more stuff...
I have forked your repo and made some changes in my local repo,
Now I want to build and test it in my swarm pool.

Can you please provide me instructions and commands to build new docker image from my local code, So I can test it.

**Comment by yandeu** [comment]
I believe it is just `npm run build && docker build .`

**Comment by alloc7260** [comment]
I have checked that it also installed in 

![npm list](https://github.com/yandeu/docker-swarm-visualizer/assets/101977910/9bc07eee-d7c6-4027-b5af-5b533ea60382)
