### ISSUE TITLE
worker not show container running

### ISSUE THREAD

**Issue by febrimaulana** [yandeu/docker-swarm-visualizer#3]
![image](https://user-images.githubusercontent.com/30101915/144472203-3ca2524c-7d3a-40bb-9e36-74cacdec98d5.png)

i am trying to run 1 node manager 2 node worker.

on the worker node there is no visual container running as shown above.

if I check using docker ps on the worker there is a container running.

the visuals also don't see the status of the disk, cpu, memory on the worker

what do I have to do ?

**Comment by yandeu** [comment]
Have you used the stack file from the "Getting Started" in [README.md](https://github.com/yandeu/docker-swarm-visualizer#readme)?

**Comment by yandeu** [comment]
Also check:

> - Make sure you can access your swarm on port 9500/tcp.
> 
> - Make sure the nodes can communicate with each other on port 9501/tcp.

**Comment by febrimaulana** [comment]
I've opened ports 9500 and 9501.

but the worker still can't see the running container and disk memory etc.

**Comment by yandeu** [comment]
I will have a closer look very soon.

**Comment by yandeu** [comment]
I just tried it and it worked as expected. Please try temporarily to allow ALL traffic.

**Comment by yandeu** [comment]
Make sure the default Docker Swarm ports are open as well:

> TCP port 2377 for cluster management communications
> TCP and UDP port 7946 for communication among nodes
> UDP port 4789 for overlay network traffic

And outgoing traffic needs to be open on TCP and UDP as well.
