### ISSUE TITLE
Missing Docker Hub repo

### ISSUE THREAD

**Issue by doneforaiur** [yandeu/docker-swarm-visualizer#4]
Hi Yannick!

Your Docker Hub profile ([https://hub.docker.com/r/yandeu/visualizer](https://hub.docker.com/r/yandeu/visualizer)) seems to be empty. However I can pull your repository to my local machine, so I guess the problem lies with Docker Hub itself... Just wanted to be sure

**Comment by yandeu** [comment]
Did you pull it with the :dev tag?
`docker pull yandeu/visualizer:dev`
