### ISSUE TITLE
Docker swarm is not scaling up or down 

### ISSUE THREAD

**Issue by mordeve** [yandeu/docker-swarm-visualizer#5]
Docker swarm is not scaling up or down when I started a heavy work.

**Comment by mordeve** [comment]
![resim](https://user-images.githubusercontent.com/46994754/151977461-561109d9-7ba8-42f3-af01-c8dcdfe39d2b.png)

**Comment by yandeu** [comment]
Have you configured the autoscaler settings?
https://github.com/yandeu/docker-swarm-visualizer#autoscaler

**Comment by mordeve** [comment]
I was configured them inside the tools.stack.yml file. I moved them inside visualizer.stack.yml now it works thank you.
