### ISSUE TITLE
Requests after scaling up

### ISSUE THREAD

**Issue by mordeve** [yandeu/docker-swarm-visualizer#6]
The moment a service is scaled up, it is not immediately ready, but still accepts requests then returns an error until being ready. Is there a solution to avoid this?

**Comment by yandeu** [comment]
If I understand it correctly, you scale up a custom service of you, which takes some times to be ready?

Read: https://stackoverflow.com/questions/53289950/clarification-on-docker-composes-start-period-paramter

**Comment by mordeve** [comment]
Thank you so much. That solves my problem.
